#!/usr/bin/env ruby

require 'chef'
require 'fileutils'
require 'chef/local_mode'

current_dir = File.dirname(__FILE__)
repo_directory = File.join(current_dir, '..', 'chef-zero-local')

FileUtils.mkdir_p(repo_directory) unless File.exist?(repo_directory)

Chef::Config.chef_repo_path = repo_directory
Chef::Config.local_mode = true
Chef::Config.versioned_cookbooks = true
Chef::Config.chef_zero.port = 7788

zero_url = Chef::LocalMode.setup_server_connectivity
puts "I have started chef-zero at #{zero_url}."
puts 'Hit Ctrl + C to end.'

Signal.trap('SIGINT') do
  Chef::LocalMode.destroy_server_connectivity
  puts 'chef-zero stopped.'
  exit
end

sleep
